services:
  solarwatch:
    build:
      context: .
      dockerfile: SolarWatch/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./SolarWatch/.env
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./SolarWatch/.env
    ports:
      - "1433:1433"
